version: "3.8"

services:
  db:
    image: mysql:8.4
    container_name: mysql8
    restart: always
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      # PMA_USER: ${MYSQL_USER}
      # PMA_PASSWORD: ${MYSQL_PASSWORD}
      PMA_AUTH_TYPE: cookie # NEED LOGIN
    ports:
      - "${PMA_PORT}:80"
    depends_on:
      - db

  backend:
    build:
      context: ./backend/monolithic
      dockerfile: Dockerfile
    container_name: nestjs-backend
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      NODE_ENV: ${NODE_ENV}
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    restart: always
    ports:
      - "3001:80"
    depends_on:
      - backend

volumes:
  db_data:
