import type { Course } from '../services/course/course.service';
import type { LearningPath } from '../services/learning-path/learning-path.service';
import type { Enrollment } from '../services/enrollment/enrollment.service';

const MOCK_USER = {
    userId: 1,
    fullName: 'Dr. John Doe',
    email: 'john.doe@edtech.com',
    avatar: null,
};

export const MOCK_COURSES: Course[] = [
    {
        courseId: 1,
        title: 'ReactJS Cơ Bản đến Nâng Cao',
        status: 'approved',
        description: 'Làm chủ React hook, Custom Hooks, Redux Toolkit, Context API và tối ưu hiệu năng ứng dụng.',
        thumbnailUrl: null,
        projectUrl: null,
        language: 'Vietnamese',
        duration: 12,
        totalLessons: 24,
        enrollmentCount: 1540,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        user: MOCK_USER,
    },
    {
        courseId: 2,
        title: 'Xây Dựng REST APIs với Node.js & Express',
        status: 'approved',
        description: 'Tự tay thiết kế hệ thống RESTful API chuẩn REST, bảo mật với JWT, kết nối MongoDB/PostgreSQL.',
        thumbnailUrl: null,
        projectUrl: null,
        language: 'Vietnamese',
        duration: 16,
        totalLessons: 30,
        enrollmentCount: 980,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        user: MOCK_USER,
    },
    {
        courseId: 3,
        title: 'Thiết Kế Giao Diện UI/UX cơ bản Figma',
        status: 'approved',
        description: 'Học cách thiết kế Wireframe, Prototype và tạo UI Components chuẩn Figma từ chuyên gia thiết kế.',
        thumbnailUrl: null,
        projectUrl: null,
        language: 'Vietnamese',
        duration: 8,
        totalLessons: 15,
        enrollmentCount: 2200,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        user: MOCK_USER,
    },
    {
        courseId: 4,
        title: 'Làm chủ TypeScript cho React',
        status: 'approved',
        description: 'Đi từ cơ bản đến nâng cao TS: Generics, Mapped Types, tsconfig và áp dụng thực tế vào React.',
        thumbnailUrl: null,
        projectUrl: null,
        language: 'Vietnamese',
        duration: 10,
        totalLessons: 20,
        enrollmentCount: 1250,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        user: MOCK_USER,
    },
    {
        courseId: 5,
        title: 'Docker cho Lập Trình Viên',
        status: 'approved',
        description: 'Container hóa ứng dụng Node/React, thiết lập Docker Compose cho môi trường phát triển và production.',
        thumbnailUrl: null,
        projectUrl: null,
        language: 'English',
        duration: 10,
        totalLessons: 18,
        enrollmentCount: 890,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        user: MOCK_USER,
    },
    {
        courseId: 6,
        title: 'GraphQL API Design',
        status: 'approved',
        description: 'Thiết lập Schema, Query, Mutation và Apollo Client để tối ưu hóa truyền tải dữ liệu.',
        thumbnailUrl: null,
        projectUrl: null,
        language: 'English',
        duration: 8,
        totalLessons: 14,
        enrollmentCount: 650,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        user: MOCK_USER,
    },
    {
        courseId: 7,
        title: 'Kiểm Thử Ứng Dụng với Vitest',
        status: 'approved',
        description: 'Viết Unit Test, Integration Test và Component Test cho React cực kỳ nhanh chóng bằng Vitest.',
        thumbnailUrl: null,
        projectUrl: null,
        language: 'Vietnamese',
        duration: 5,
        totalLessons: 10,
        enrollmentCount: 420,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        user: MOCK_USER,
    },
    {
        courseId: 8,
        title: 'Lập trình Java Web với Spring Boot',
        status: 'approved',
        description: 'Xây dựng ứng dụng Enterprise hoàn chỉnh với Spring Boot, Spring Security, JPA/Hibernate.',
        thumbnailUrl: null,
        projectUrl: null,
        language: 'Vietnamese',
        duration: 20,
        totalLessons: 35,
        enrollmentCount: 1820,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        user: MOCK_USER,
    },
    {
        courseId: 9,
        title: 'Next.js 14 - Production-Grade Applications',
        status: 'approved',
        description: 'Deep dive into App Router, Server Actions, SSR, ISR, and layout optimizations for web apps.',
        thumbnailUrl: null,
        projectUrl: null,
        language: 'English',
        duration: 14,
        totalLessons: 28,
        enrollmentCount: 2100,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        user: MOCK_USER,
    },
    {
        courseId: 10,
        title: 'Xây dựng microservices với NestJS & RabbitMQ',
        status: 'approved',
        description: 'Thiết kế hệ thống phân tán chịu tải cao sử dụng NestJS, RabbitMQ, Redis và PostgreSQL.',
        thumbnailUrl: null,
        projectUrl: null,
        language: 'Vietnamese',
        duration: 18,
        totalLessons: 32,
        enrollmentCount: 950,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        user: MOCK_USER,
    },
    {
        courseId: 11,
        title: 'Clean Code & Refactoring cho Developer',
        status: 'approved',
        description: 'Học cách viết code sạch, dễ bảo trì, áp dụng SOLID design principles và các kỹ thuật refactoring.',
        thumbnailUrl: null,
        projectUrl: null,
        language: 'Vietnamese',
        duration: 6,
        totalLessons: 12,
        enrollmentCount: 1430,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        user: MOCK_USER,
    },
    {
        courseId: 12,
        title: 'Cấu trúc dữ liệu và Giải thuật cơ bản',
        status: 'approved',
        description: 'Làm chủ các cấu trúc dữ liệu quan trọng như Array, LinkedList, Tree, Graph và các thuật toán tìm kiếm, sắp xếp.',
        thumbnailUrl: null,
        projectUrl: null,
        language: 'Vietnamese',
        duration: 15,
        totalLessons: 30,
        enrollmentCount: 3200,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        user: MOCK_USER,
    },
    {
        courseId: 13,
        title: 'DevOps & CI/CD Pipelines with GitHub Actions',
        status: 'approved',
        description: 'Build robust automation pipelines for testing, building, and deploying applications directly on GitHub.',
        thumbnailUrl: null,
        projectUrl: null,
        language: 'English',
        duration: 12,
        totalLessons: 22,
        enrollmentCount: 1120,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        user: MOCK_USER,
    },
    {
        courseId: 14,
        title: 'Cơ sở dữ liệu SQL từ số 0',
        status: 'approved',
        description: 'Học cách thiết kế cơ sở dữ liệu quan hệ, viết các câu lệnh truy vấn phức tạp từ đơn giản đến nâng cao.',
        thumbnailUrl: null,
        projectUrl: null,
        language: 'Vietnamese',
        duration: 10,
        totalLessons: 20,
        enrollmentCount: 2500,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        user: MOCK_USER,
    },
    {
        courseId: 15,
        title: 'Tailwind CSS - Modern & Responsive Layouts',
        status: 'approved',
        description: 'Create gorgeous, highly responsive layouts in minutes using Tailwind utility-first CSS framework.',
        thumbnailUrl: null,
        projectUrl: null,
        language: 'English',
        duration: 6,
        totalLessons: 12,
        enrollmentCount: 1670,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        user: MOCK_USER,
    },
    {
        courseId: 16,
        title: 'Vue.js 3 & Pinia State Management',
        status: 'approved',
        description: 'Làm quen với Composition API, SFCs, Router và quản lý state tập trung hiệu quả bằng Pinia.',
        thumbnailUrl: null,
        projectUrl: null,
        language: 'Vietnamese',
        duration: 12,
        totalLessons: 24,
        enrollmentCount: 810,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        user: MOCK_USER,
    },
    {
        courseId: 17,
        title: 'Python cho Khoa học Dữ liệu (Data Science)',
        status: 'approved',
        description: 'Sử dụng NumPy, Pandas, Matplotlib và Scikit-Learn để phân tích, trực quan hóa và xây dựng mô hình dự báo.',
        thumbnailUrl: null,
        projectUrl: null,
        language: 'Vietnamese',
        duration: 18,
        totalLessons: 36,
        enrollmentCount: 2900,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        user: MOCK_USER,
    },
    {
        courseId: 18,
        title: 'Thiết kế hệ thống System Design cơ bản',
        status: 'approved',
        description: 'Hiểu các khái niệm Load Balancing, Caching, Databases Sharding, CAP Theorem cho hệ thống triệu người dùng.',
        thumbnailUrl: null,
        projectUrl: null,
        language: 'Vietnamese',
        duration: 14,
        totalLessons: 26,
        enrollmentCount: 1750,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        user: MOCK_USER,
    },
    {
        courseId: 19,
        title: 'Xây dựng Ứng dụng Di động với React Native',
        status: 'approved',
        description: 'Phát triển ứng dụng Android/iOS đa nền tảng sử dụng component bản địa, Navigation và Redux.',
        thumbnailUrl: null,
        projectUrl: null,
        language: 'Vietnamese',
        duration: 16,
        totalLessons: 30,
        enrollmentCount: 1200,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        user: MOCK_USER,
    },
    {
        courseId: 20,
        title: 'Bảo mật Web OWASP Top 10 cơ bản',
        status: 'approved',
        description: 'Phòng chống SQL Injection, XSS, CSRF và các lỗ hổng phổ biến bảo vệ ứng dụng web.',
        thumbnailUrl: null,
        projectUrl: null,
        language: 'Vietnamese',
        duration: 8,
        totalLessons: 16,
        enrollmentCount: 680,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        user: MOCK_USER,
    },
    {
        courseId: 21,
        title: 'Kubernetes in Practice for DevOps',
        status: 'approved',
        description: 'Deploy, scale, and manage containerized applications with Kubernetes pods, services, and deployments.',
        thumbnailUrl: null,
        projectUrl: null,
        language: 'English',
        duration: 15,
        totalLessons: 26,
        enrollmentCount: 920,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        user: MOCK_USER,
    },
    {
        courseId: 22,
        title: 'Trí tuệ nhân tạo & Lập trình AI Agent cơ bản',
        status: 'approved',
        description: 'Tích hợp OpenAI API, thiết kế Prompt Engineering và xây dựng RAG Agent ứng dụng thực tế.',
        thumbnailUrl: null,
        projectUrl: null,
        language: 'Vietnamese',
        duration: 12,
        totalLessons: 22,
        enrollmentCount: 2050,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        user: MOCK_USER,
    }
];

export const MOCK_LEARNING_PATHS: LearningPath[] = [
    {
        learningPathId: 1,
        title: 'Frontend Mastery Path',
        description: 'Trở thành Frontend Engineer chuyên nghiệp từ thiết kế UI đến lập trình React/TS.',
        slug: 'frontend-mastery',
        bannerUrl: null,
        level: 'intermediate',
        createdAt: new Date().toISOString(),
        learningPathCourses: [
            { learningPathId: 1, courseId: 3, position: 1, course: MOCK_COURSES[2] },
            { learningPathId: 1, courseId: 1, position: 2, course: MOCK_COURSES[0] },
            { learningPathId: 1, courseId: 4, position: 3, course: MOCK_COURSES[3] }
        ]
    },
    {
        learningPathId: 2,
        title: 'Full-Stack Developer Path',
        description: 'Lộ trình kết hợp tối ưu ReactJS, Node.js API và công cụ containerization Docker.',
        slug: 'full-stack-engineering',
        bannerUrl: null,
        level: 'advanced',
        createdAt: new Date().toISOString(),
        learningPathCourses: [
            { learningPathId: 2, courseId: 1, position: 1, course: MOCK_COURSES[0] },
            { learningPathId: 2, courseId: 2, position: 2, course: MOCK_COURSES[1] },
            { learningPathId: 2, courseId: 5, position: 3, course: MOCK_COURSES[4] }
        ]
    },
    {
        learningPathId: 3,
        title: 'UI/UX Product Design Path',
        description: 'Lộ trình cơ bản làm quen thiết kế giao diện ứng dụng và trải nghiệm người dùng.',
        slug: 'product-design',
        bannerUrl: null,
        level: 'beginner',
        createdAt: new Date().toISOString(),
        learningPathCourses: [
            { learningPathId: 3, courseId: 3, position: 1, course: MOCK_COURSES[2] }
        ]
    },
    {
        learningPathId: 4,
        title: 'Backend Mastery Path',
        description: 'Học cách thiết kế REST API, quản lý cơ sở dữ liệu và tối ưu hệ thống backend vững chắc.',
        slug: 'backend-mastery',
        bannerUrl: null,
        level: 'intermediate',
        createdAt: new Date().toISOString(),
        learningPathCourses: [
            { learningPathId: 4, courseId: 14, position: 1, course: MOCK_COURSES[13] },
            { learningPathId: 4, courseId: 2, position: 2, course: MOCK_COURSES[1] },
            { learningPathId: 4, courseId: 8, position: 3, course: MOCK_COURSES[7] }
        ]
    },
    {
        learningPathId: 5,
        title: 'DevOps Engineer Career Path',
        description: 'Lộ trình làm chủ Docker, Kubernetes, CI/CD và kiến trúc hạ tầng hiện đại.',
        slug: 'devops-engineer',
        bannerUrl: null,
        level: 'advanced',
        createdAt: new Date().toISOString(),
        learningPathCourses: [
            { learningPathId: 5, courseId: 5, position: 1, course: MOCK_COURSES[4] },
            { learningPathId: 5, courseId: 13, position: 2, course: MOCK_COURSES[12] },
            { learningPathId: 5, courseId: 21, position: 3, course: MOCK_COURSES[20] }
        ]
    },
    {
        learningPathId: 6,
        title: 'Mobile Developer Path',
        description: 'Từ giao diện UI/UX Figma đến việc hoàn thiện ứng dụng di động đa nền tảng bằng React Native.',
        slug: 'mobile-developer',
        bannerUrl: null,
        level: 'intermediate',
        createdAt: new Date().toISOString(),
        learningPathCourses: [
            { learningPathId: 6, courseId: 3, position: 1, course: MOCK_COURSES[2] },
            { learningPathId: 6, courseId: 1, position: 2, course: MOCK_COURSES[0] },
            { learningPathId: 6, courseId: 19, position: 3, course: MOCK_COURSES[18] }
        ]
    },
    {
        learningPathId: 7,
        title: 'Data Science & AI Foundations',
        description: 'Tìm hiểu ngôn ngữ Python, xử lý dữ liệu và tiếp cận thế giới Trí Tuệ Nhân Tạo cơ bản.',
        slug: 'data-science-ai',
        bannerUrl: null,
        level: 'beginner',
        createdAt: new Date().toISOString(),
        learningPathCourses: [
            { learningPathId: 7, courseId: 17, position: 1, course: MOCK_COURSES[16] },
            { learningPathId: 7, courseId: 22, position: 2, course: MOCK_COURSES[21] }
        ]
    },
    {
        learningPathId: 8,
        title: 'Software Architecture & System Design',
        description: 'Làm chủ thiết kế hệ thống lớn, NestJS Microservices và các nguyên lý Clean Code.',
        slug: 'software-architect',
        bannerUrl: null,
        level: 'advanced',
        createdAt: new Date().toISOString(),
        learningPathCourses: [
            { learningPathId: 8, courseId: 11, position: 1, course: MOCK_COURSES[10] },
            { learningPathId: 8, courseId: 10, position: 2, course: MOCK_COURSES[9] },
            { learningPathId: 8, courseId: 18, position: 3, course: MOCK_COURSES[17] }
        ]
    },
    {
        learningPathId: 9,
        title: 'Full-Stack Vue.js Developer',
        description: 'Kết hợp Vue.js 3 hiện đại phía Frontend và Node.js Express phía Backend.',
        slug: 'vue-fullstack',
        bannerUrl: null,
        level: 'intermediate',
        createdAt: new Date().toISOString(),
        learningPathCourses: [
            { learningPathId: 9, courseId: 16, position: 1, course: MOCK_COURSES[15] },
            { learningPathId: 9, courseId: 2, position: 2, course: MOCK_COURSES[1] }
        ]
    }
];

export const MOCK_ENROLLMENTS: Enrollment[] = [
    {
        enrollmentId: 101,
        enrolledAt: new Date().toISOString(),
        status: 'active',
        progress: 52,
        lastAccessedAt: new Date().toISOString(),
        completedAt: null,
        expiresAt: null,
        course: MOCK_COURSES[0],
    },
    {
        enrollmentId: 102,
        enrolledAt: new Date().toISOString(),
        status: 'active',
        progress: 31,
        lastAccessedAt: new Date(Date.now() - 3600000).toISOString(),
        completedAt: null,
        expiresAt: null,
        course: MOCK_COURSES[1],
    },
    {
        enrollmentId: 103,
        enrolledAt: new Date().toISOString(),
        status: 'completed',
        progress: 100,
        lastAccessedAt: new Date(Date.now() - 86400000).toISOString(),
        completedAt: new Date(Date.now() - 86400000).toISOString(),
        expiresAt: null,
        course: MOCK_COURSES[2],
    }
];

export const MOCK_PROFILE = {
    fullName: 'Nguyễn Văn Learner',
    email: 'learner@edtech.com',
    streakCount: 12,
    completedCourses: 1,
    learningHours: 124,
    enrolledPaths: 2,
};

export const MOCK_LEARNER_PROFILE_FULL = {
    fullName: 'Nguyễn Văn Learner',
    email: 'learner@edtech.com',
    avatarUrl: null,
    learningGoal: 'Master React and Node.js for Fullstack',
    level: 'Intermediate',
    createdAt: '2026-06-01T08:00:00Z',
    bio: 'Học viên năng nổ học hỏi công nghệ mới.',
};

export const MOCK_ACADEMIC_PROFILE = {
    fullName: 'Trần Thị Provider',
    email: 'provider@edtech.com',
    avatarUrl: null,
    expertise: 'Software Architecture & React',
    experienceYears: 8,
    createdAt: '2026-05-15T10:00:00Z',
    bio: 'Dạy học với cả trái tim và kinh nghiệm thực chiến.',
};

export const MOCK_USERS_BACKEND = [
    {
        userId: 1,
        fullName: 'Nguyễn Văn Learner',
        email: 'learner@edtech.com',
        role: { roleName: 'learner' },
        isEmailVerified: true,
        createdAt: '2026-06-01T08:00:00Z',
        updatedAt: '2026-06-07T12:00:00Z',
        avatar: null
    },
    {
        userId: 2,
        fullName: 'Trần Thị Provider',
        email: 'provider@edtech.com',
        role: { roleName: 'course provider' },
        isEmailVerified: true,
        createdAt: '2026-05-15T10:00:00Z',
        updatedAt: '2026-06-05T09:30:00Z',
        avatar: null
    },
    {
        userId: 3,
        fullName: 'Lê Văn Manager',
        email: 'manager@edtech.com',
        role: { roleName: 'academic manager' },
        isEmailVerified: true,
        createdAt: '2026-04-20T14:00:00Z',
        updatedAt: '2026-06-01T11:15:00Z',
        avatar: null
    },
    {
        userId: 4,
        fullName: 'Phạm Hồng Admin',
        email: 'admin@edtech.com',
        role: { roleName: 'admin' },
        isEmailVerified: true,
        createdAt: '2026-01-10T09:00:00Z',
        updatedAt: '2026-06-07T18:00:00Z',
        avatar: null
    },
    {
        userId: 5,
        fullName: 'Nguyễn Thị Hoa',
        email: 'hoa.nt@example.com',
        role: { roleName: 'learner' },
        isEmailVerified: false,
        createdAt: '2026-06-06T15:45:00Z',
        updatedAt: '2026-06-06T15:45:00Z',
        avatar: null
    }
];
